#!/usr/bin/env bash

# This script will print some metadata about a media file for transcoding consideration using ffprobe.

FILE=$1
set -x
ffprobe -v quiet -print_format json -show_entries stream=codec_type,bit_rate,codec_name,width,height,color_primaries,codec_tag_string -show_entries format=bit_rate "$FILE"
