#!/usr/bin/env bash

# This script will print the bit rate of a video file

FILE=$1
set -x
ffprobe -v quiet -print_format json -show_entries stream=codec_type,bit_rate,codec_name,width,height,color_primaries,codec_tag_string -show_entries format=bit_rate "$FILE"
